@startuml

/'central controller
currentUser used to distinguish user type, student or adminstaff or ep by access users
'/
class EventsApp {
    - currentUser: AuthenticatingUser 
    - users: Collection<AuthenticatingUser>
    - events: Collection<Events>
    + login(email: String, Password: String): void
    + logout(): void
    + registerEntertainmentProvider()
    + createEvent()
    + searchPerformances()
    + viewPerformance()
    + bookPerformance()
    + editPreferences()
    + cancelPerformance(performanceID: String, message: String): void
    + cancelBooking(bookingNumber: String): void
    + reviewPerformance()
    + sponsorPerformance()
}

abstract class AuthenticatingUser {
    - userID: String
    - email: String
    - password: String
}

class EntertainmentProvider {
    - name: String
    - businessNumber: String
    - description: String
}

class AdminStaff {
}

class Student {
    - preferences: Collection<EventType>
}

class Performance {
    - performanceID: String
    - startDateTime: Date
    - endDateTime: Date 
    - performerNames: Collection<string>
    - ticketPrice: double
    - remainingTickets: int
    - venueAddress: String 
    - isOutdoor: Boolean
    - isSmoking: Boolean
    + applySponsorship(amount: double): void
}

class Booking {
    - bookingNumber: String
    - numTickets: int
    - studentName: String
    - contactEmail: String
    - contactPhone: String
}

class Review {
    - performanceID: String
    - rating: int
    - comment: String
}

class Event {
    - eventID: String
    - title: String
    - type: EventType
    - isTicketed: Boolean
    + getAverageRating(): double
}

interface VerificationSystem {
    + verifyBusiness(businessNumber: String): Boolean
}

interface PaymentSystem {
    + processPayment(amount: double, userID: String): Boolean
    + processRefund(amount: double, userID: String): void
}

enum EventType {
   Music
   Theatre
   Dance
   Movie
   Sports
   Games
}


EventsApp "1" -- "0..*" AuthenticatingUser
EventsApp "1" -- "0..*" Event
EventsApp ..> PaymentSystem
EventsApp ..> VerificationSystem

AuthenticatingUser <|-- AdminStaff
AuthenticatingUser <|-- EntertainmentProvider
AuthenticatingUser <|-- Student

Student "1" -- "0..*" Review
Student "1" -- "0..*" Booking


Booking "0..*" -- "1" Performance
Performance "0..*" -- "1" Event
Event "0..*" -- "1" EntertainmentProvider
Event "1" -- "0..*" Review
@enduml
